import test from 'node:test';
import assert from 'node:assert/strict';
import { generateSchemaDDL } from '../../../src/utils/schema.js';

test('generateSchemaDDL builds CREATE TABLE for mysql with primary and foreign keys', () => {
  const ddl = generateSchemaDDL({
    driver: 'mysql',
    tableName: 'orders',
    tableType: 'table',
    columns: [
      { name: 'id', type: 'BIGINT', nullable: 'No', isPrimary: true, extra: 'auto_increment' },
      { name: 'user_id', type: 'BIGINT', nullable: 'No', isForeign: true, foreignTable: 'users', foreignCol: 'id' },
      { name: 'status', type: 'VARCHAR(20)', nullable: 'No', extra: "'draft'" },
    ],
  });

  assert.match(ddl, /CREATE TABLE `orders`/);
  assert.match(ddl, /`id` BIGINT NOT NULL AUTO_INCREMENT/);
  assert.match(ddl, /PRIMARY KEY \(`id`\)/);
  assert.match(ddl, /FOREIGN KEY \(`user_id`\) REFERENCES `users` \(`id`\)/);
  assert.match(ddl, /`status` VARCHAR\(20\) NOT NULL DEFAULT 'draft'/);
});

test('generateSchemaDDL maps auto increment to identity for pgsql', () => {
  const ddl = generateSchemaDDL({
    driver: 'pgsql',
    tableName: 'users',
    tableType: 'table',
    columns: [{ name: 'id', type: 'INTEGER', nullable: 'No', isPrimary: true, extra: 'auto_increment' }],
  });

  assert.match(ddl, /CREATE TABLE "users"/);
  assert.match(ddl, /"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY/);
});

test('generateSchemaDDL returns placeholder definition for views', () => {
  const ddl = generateSchemaDDL({
    driver: 'mysql',
    tableName: 'active_users',
    tableType: 'view',
    columns: [],
  });

  assert.match(ddl, /CREATE VIEW `active_users` AS/);
  assert.match(ddl, /View definition is not fetched from the server yet/);
});
