export const themes = {
  emerald: {
    nameKey: 'emerald',
    text: 'text-emerald-500',
    textLight: 'text-emerald-400',
    textLightOpacity: 'text-emerald-400/80',
    textLightest: 'text-emerald-100',
    bg: 'bg-emerald-600',
    hoverBg: 'hover:bg-emerald-500',
    lightBg: 'bg-emerald-500/10',
    border: 'border-emerald-500',
    borderLight: 'border-emerald-500/20',
    focusRing: 'focus:border-emerald-500 focus:ring-1 focus:ring-emerald-500 focus:outline-none',
    accentBg: 'bg-emerald-500',
    accent: 'accent-emerald-500',
    selection: 'selection:bg-emerald-500/30',
    previewClass: 'bg-emerald-500',
    badgeBg: 'bg-emerald-500/20',
    badgeText: 'text-emerald-300',
  },
  blue: {
    nameKey: 'blue',
    text: 'text-blue-500',
    textLight: 'text-blue-400',
    textLightOpacity: 'text-blue-400/80',
    textLightest: 'text-blue-100',
    bg: 'bg-blue-600',
    hoverBg: 'hover:bg-blue-500',
    lightBg: 'bg-blue-500/10',
    border: 'border-blue-500',
    borderLight: 'border-blue-500/20',
    focusRing: 'focus:border-blue-500 focus:ring-1 focus:ring-blue-500 focus:outline-none',
    accentBg: 'bg-blue-500',
    accent: 'accent-blue-500',
    selection: 'selection:bg-blue-500/30',
    previewClass: 'bg-blue-500',
    badgeBg: 'bg-blue-500/20',
    badgeText: 'text-blue-300',
  },
  violet: {
    nameKey: 'violet',
    text: 'text-violet-500',
    textLight: 'text-violet-400',
    textLightOpacity: 'text-violet-400/80',
    textLightest: 'text-violet-100',
    bg: 'bg-violet-600',
    hoverBg: 'hover:bg-violet-500',
    lightBg: 'bg-violet-500/10',
    border: 'border-violet-500',
    borderLight: 'border-violet-500/20',
    focusRing: 'focus:border-violet-500 focus:ring-1 focus:ring-violet-500 focus:outline-none',
    accentBg: 'bg-violet-500',
    accent: 'accent-violet-500',
    selection: 'selection:bg-violet-500/30',
    previewClass: 'bg-violet-500',
    badgeBg: 'bg-violet-500/20',
    badgeText: 'text-violet-300',
  },
  amber: {
    nameKey: 'amber',
    text: 'text-amber-500',
    textLight: 'text-amber-400',
    textLightOpacity: 'text-amber-400/80',
    textLightest: 'text-amber-100',
    bg: 'bg-amber-600',
    hoverBg: 'hover:bg-amber-500',
    lightBg: 'bg-amber-500/10',
    border: 'border-amber-500',
    borderLight: 'border-amber-500/20',
    focusRing: 'focus:border-amber-500 focus:ring-1 focus:ring-amber-500 focus:outline-none',
    accentBg: 'bg-amber-500',
    accent: 'accent-amber-500',
    selection: 'selection:bg-amber-500/30',
    previewClass: 'bg-amber-500',
    badgeBg: 'bg-amber-500/20',
    badgeText: 'text-amber-300',
  },
  rose: {
    nameKey: 'rose',
    text: 'text-rose-500',
    textLight: 'text-rose-400',
    textLightOpacity: 'text-rose-400/80',
    textLightest: 'text-rose-100',
    bg: 'bg-rose-600',
    hoverBg: 'hover:bg-rose-500',
    lightBg: 'bg-rose-500/10',
    border: 'border-rose-500',
    borderLight: 'border-rose-500/20',
    focusRing: 'focus:border-rose-500 focus:ring-1 focus:ring-rose-500 focus:outline-none',
    accentBg: 'bg-rose-500',
    accent: 'accent-rose-500',
    selection: 'selection:bg-rose-500/30',
    previewClass: 'bg-rose-500',
    badgeBg: 'bg-rose-500/20',
    badgeText: 'text-rose-300',
  },
};
