export default function useWorkspaceColumnTypeHelpers({ formData }) {
  const getColumnType = (column) => String(column?.type || '').toLowerCase();

  const isAutoGeneratedColumn = (column) => {
    const extra = String(column?.extra || '').toLowerCase();
    return extra.includes('auto_increment') || extra.includes('nextval(');
  };

  const isBooleanColumn = (column) => {
    const type = getColumnType(column);
    return (
      /(^|[^a-z])(bool|boolean)([^a-z]|$)/.test(type) ||
      /^tinyint\(1\)/.test(type) ||
      /^bit\(1\)/.test(type)
    );
  };

  const isDateTimeColumn = (column) => {
    const type = getColumnType(column);
    return type.includes('datetime') || type.includes('timestamp');
  };

  const isDateColumn = (column) => getColumnType(column) === 'date';

  const isTimeColumn = (column) => {
    const type = getColumnType(column);
    return type === 'time' || (type.includes('time') && !isDateTimeColumn(column));
  };

  const isNumericColumnType = (column) => {
    const type = getColumnType(column);
    if (isBooleanColumn(column)) return false;
    return /(bigint|smallint|mediumint|tinyint|int|decimal|numeric|float|double|real|serial)/.test(
      type,
    );
  };

  const isLongTextColumn = (column) => /(text|json|blob|clob)/.test(getColumnType(column));

  const normalizeTemporalInputValue = (value, inputType) => {
    if (value === null || value === undefined || value === '') return '';
    const raw = String(value).trim();
    if (inputType === 'datetime-local') {
      return raw.replace(' ', 'T').slice(0, 19);
    }
    if (inputType === 'date') {
      return raw.slice(0, 10);
    }
    if (inputType === 'time') {
      return raw.slice(0, 8);
    }
    return raw;
  };

  const getInputValue = (columnName) => formData[columnName] ?? '';

  return {
    isAutoGeneratedColumn,
    isBooleanColumn,
    isDateTimeColumn,
    isDateColumn,
    isTimeColumn,
    isNumericColumnType,
    isLongTextColumn,
    normalizeTemporalInputValue,
    getInputValue,
  };
}
