function quoteIdentifier(driver, name) {
  if (driver === 'pgsql') {
    return `"${String(name).replace(/"/g, '""')}"`;
  }

  return `\`${String(name).replace(/`/g, '``')}\``;
}

function formatDefault(defaultValue) {
  if (defaultValue === null || defaultValue === undefined || defaultValue === '') {
    return '';
  }

  return ` DEFAULT ${String(defaultValue)}`;
}

function formatColumnLine(driver, column) {
  const parts = [quoteIdentifier(driver, column.name), String(column.type || 'TEXT')];

  if (column.nullable === 'No') {
    parts.push('NOT NULL');
  }

  if (
    column.extra &&
    String(column.extra).trim() !== '' &&
    !String(column.extra).includes('auto_increment')
  ) {
    const extraValue = String(column.extra).trim();
    const normalized = extraValue.toUpperCase();
    if (!normalized.startsWith('DEFAULT')) {
      parts.push(formatDefault(extraValue).trim());
    } else {
      parts.push(extraValue);
    }
  }

  if (
    String(column.extra || '')
      .toLowerCase()
      .includes('auto_increment')
  ) {
    parts.push(driver === 'pgsql' ? 'GENERATED BY DEFAULT AS IDENTITY' : 'AUTO_INCREMENT');
  }

  return `  ${parts.join(' ')}`.trimEnd();
}

export function generateSchemaDDL({ driver, tableName, tableType, columns }) {
  const safeDriver = driver === 'pgsql' ? 'pgsql' : 'mysql';
  const name = tableName || 'table_name';
  const quotedName = quoteIdentifier(safeDriver, name);
  const normalizedType = String(tableType || 'table').toLowerCase();
  const safeColumns = Array.isArray(columns) ? columns : [];

  if (normalizedType === 'view') {
    return [
      `CREATE VIEW ${quotedName} AS`,
      '  -- View definition is not fetched from the server yet.',
      '  -- This panel only has schema metadata for the selected view.',
      '  SELECT 1;',
    ].join('\n');
  }

  const columnLines = safeColumns.map((column) => formatColumnLine(safeDriver, column));
  const primaryKeys = safeColumns
    .filter((column) => column.isPrimary)
    .map((column) => quoteIdentifier(safeDriver, column.name));

  if (primaryKeys.length > 0) {
    columnLines.push(`  PRIMARY KEY (${primaryKeys.join(', ')})`);
  }

  safeColumns
    .filter((column) => column.isForeign && column.foreignTable && column.foreignCol)
    .forEach((column) => {
      columnLines.push(
        `  FOREIGN KEY (${quoteIdentifier(safeDriver, column.name)}) REFERENCES ${quoteIdentifier(safeDriver, column.foreignTable)} (${quoteIdentifier(safeDriver, column.foreignCol)})`,
      );
    });

  return `CREATE TABLE ${quotedName} (\n${columnLines.join(',\n')}\n);`;
}
