import test from 'node:test';
import assert from 'node:assert/strict';
import createWorkspaceImportExportActions from '../../../../../src/hooks/workspace/actions/useWorkspaceImportExportActions.js';

function setupDomDownloadMocks() {
  const originalDocument = globalThis.document;
  const originalCreateObjectURL = globalThis.URL?.createObjectURL;

  let capturedBlob = null;
  const capturedAnchors = [];

  globalThis.document = {
    body: {
      appendChild: () => {},
      removeChild: () => {},
    },
    createElement: (tag) => {
      assert.equal(tag, 'a');
      const attrs = {};
      const anchor = {
        attrs,
        setAttribute: (key, value) => {
          attrs[key] = value;
        },
        click: () => {
          attrs.__clicked = true;
        },
      };
      capturedAnchors.push(anchor);
      return anchor;
    },
  };

  if (!globalThis.URL) {
    globalThis.URL = class URL {};
  }

  globalThis.URL.createObjectURL = (blob) => {
    capturedBlob = blob;
    return 'blob:onedb-test';
  };

  const restore = () => {
    globalThis.document = originalDocument;

    if (originalCreateObjectURL) {
      globalThis.URL.createObjectURL = originalCreateObjectURL;
    } else if (globalThis.URL?.createObjectURL) {
      delete globalThis.URL.createObjectURL;
    }
  };

  return {
    getCapturedBlob: () => capturedBlob,
    getCapturedAnchors: () => capturedAnchors,
    restore,
  };
}

function createBaseActions(overrides = {}) {
  const toastCalls = [];
  const setModalConfigCalls = [];

  const deps = {
    t: (key) => key,
    loadJsZip: async () => {
      throw new Error('loadJsZip should not be called in this test');
    },
    loadXlsx: async () => {
      throw new Error('loadXlsx should not be called in this test');
    },
    modalConfig: { isOpen: true, type: 'export_db' },
    setModalConfig: (value) => {
      setModalConfigCalls.push(value);
    },
    importFileInputRef: { current: null },
    isImporting: false,
    setIsImporting: () => {},
    setIsImportDragActive: () => {},
    setImportLimitsError: () => {},
    importLimits: null,
    currentTableData: null,
    activeDb: 'appdb',
    activeTable: 'users',
    isAutoGeneratedColumn: () => false,
    isBooleanColumn: () => false,
    isNumericColumnType: () => false,
    quoteIdentifier: (name) => `\`${name}\``,
    escapeLiteral: (value) => {
      if (value === null || value === undefined) return 'NULL';
      return `'${String(value).replace(/'/g, "''")}'`;
    },
    callApi: async () => ({ rows: [], rowCount: 0 }),
    buildConnectionPayload: (dbName) => ({ database: dbName }),
    executeSql: async () => {},
    refreshSchemas: async () => {},
    ensureDatabaseTablesLoaded: async () => {},
    refreshActiveTable: async () => {},
    showToast: (message, type) => {
      toastCalls.push({ message, type });
    },
    databases: {
      appdb: {
        users: { type: 'table' },
      },
    },
    hiddenColumns: new Set(),
    processedData: [],
    selectedRows: new Set(),
    setSqlQuery: () => {},
    aiPrompt: '',
    setAiPrompt: () => {},
    setIsAiLoading: () => {},
    ...overrides,
  };

  return {
    actions: createWorkspaceImportExportActions(deps),
    toastCalls,
    setModalConfigCalls,
  };
}

test('handleExportDatabaseSql paginates each table and generates SQL dump', async () => {
  const dom = setupDomDownloadMocks();

  try {
    const browseCalls = [];
    const { actions, toastCalls, setModalConfigCalls } = createBaseActions({
      databases: {
        appdb: {
          users: { type: 'table' },
          logs: { type: 'table' },
          report_view: { type: 'view' },
        },
      },
      callApi: async (action, payload) => {
        assert.equal(action, 'browse_table');
        browseCalls.push(payload);

        if (payload.table === 'logs') {
          return { rowCount: 0, rows: [] };
        }

        if (payload.table === 'users' && payload.page === 1) {
          return {
            rowCount: 3,
            rows: [
              { id: 1, email: 'alpha@example.com' },
              { id: 2, email: 'beta@example.com' },
            ],
          };
        }

        if (payload.table === 'users' && payload.page === 2) {
          return {
            rowCount: 3,
            rows: [{ id: 3, email: 'gamma@example.com' }],
          };
        }

        throw new Error(`Unexpected browse payload: ${JSON.stringify(payload)}`);
      },
    });

    await actions.handleExportDatabaseSql();

    assert.equal(browseCalls.length, 3);
    assert.deepEqual(
      browseCalls.map((entry) => `${entry.table}:${entry.page}`),
      ['logs:1', 'users:1', 'users:2'],
    );

    const blob = dom.getCapturedBlob();
    assert.ok(blob, 'Expected SQL export blob to be produced');

    const sqlText = await blob.text();
    assert.match(sqlText, /-- DB: appdb/);
    assert.match(sqlText, /-- Table: logs \(0 rows\)/);
    assert.match(sqlText, /-- Table: users \(3 rows\)/);
    assert.match(sqlText, /INSERT INTO `users` \(`id`, `email`\) VALUES \(1, 'alpha@example.com'\);/);
    assert.match(sqlText, /INSERT INTO `users` \(`id`, `email`\) VALUES \(3, 'gamma@example.com'\);/);

    const anchors = dom.getCapturedAnchors();
    assert.equal(anchors.length, 1);
    assert.equal(anchors[0].attrs.download, 'appdb_full_dump.sql');
    assert.equal(anchors[0].attrs.__clicked, true);

    assert.deepEqual(setModalConfigCalls, [{ isOpen: false, type: null }]);
    assert.equal(toastCalls.at(-1)?.type, 'success');
  } finally {
    dom.restore();
  }
});

test('handleExportTable exports only selected rows and respects hidden columns', async () => {
  const dom = setupDomDownloadMocks();

  try {
    const { actions, toastCalls, setModalConfigCalls } = createBaseActions({
      activeDb: 'appdb',
      activeTable: 'users',
      processedData: [
        { _origIndex: 0, id: 1, email: 'alpha@example.com', secret: 's1' },
        { _origIndex: 1, id: 2, email: 'beta@example.com', secret: 's2' },
      ],
      selectedRows: new Set([1]),
      hiddenColumns: new Set(['secret']),
    });

    actions.handleExportTable('sql');

    const blob = dom.getCapturedBlob();
    assert.ok(blob, 'Expected SQL export blob to be produced');

    const sqlText = await blob.text();
    assert.match(sqlText, /-- DB: appdb/);
    assert.match(sqlText, /-- Table: users/);
    assert.doesNotMatch(sqlText, /secret/);
    assert.match(sqlText, /INSERT INTO "users" \("id", "email"\) VALUES \(2, 'beta@example.com'\);/);

    const anchors = dom.getCapturedAnchors();
    assert.equal(anchors.length, 1);
    assert.equal(anchors[0].attrs.download, 'users_dump.sql');

    assert.equal(toastCalls.at(-1)?.type, 'success');
    assert.deepEqual(setModalConfigCalls, [{ isOpen: false, type: null }]);
  } finally {
    dom.restore();
  }
});
