import React from 'react';
import { Key, Link as LinkIcon, Network, X } from 'lucide-react';
import SelectField from '../shared/SelectField.jsx';
import TemporalInputField from '../shared/TemporalInputField.jsx';

export default function RowFormDrawer({
  isOpen,
  modalConfig,
  setModalConfig,
  rowDetailsTab,
  setRowDetailsTab,
  relatedDataInfo,
  t,
  tc,
  saveRowData,
  currentTableData,
  formData,
  baseSelectClass,
  baseFieldClass,
  baseTextAreaClass,
  getInputValue,
  setFormData,
  databases,
  activeDb,
  isBooleanColumn,
  isDateTimeColumn,
  isDateColumn,
  isTimeColumn,
  isLongTextColumn,
  isNumericColumnType,
  isAutoGeneratedColumn,
  normalizeTemporalInputValue,
}) {
  if (!isOpen || modalConfig.type !== 'row_form') {
    return null;
  }

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm z-50 flex items-center justify-end">
      <div className="bg-[#1c1c1c] border-l border-[#333] h-full w-full max-w-md flex flex-col shadow-2xl animate-in slide-in-from-right">
        <div className="px-6 border-b border-[#2e2e32] flex justify-between items-center bg-[#18181b] shrink-0">
          <div className="flex gap-4">
            <button
              onClick={() => setRowDetailsTab('details')}
              className={`py-4 text-sm font-medium border-b-2 transition-colors flex items-center gap-2 ${rowDetailsTab === 'details' ? `${tc.border} ${tc.textLight}` : 'border-transparent text-zinc-400 hover:text-zinc-200'}`}
            >
              {modalConfig.viewOnly
                ? t('rowDetails')
                : modalConfig.editIndex > -1
                  ? t('editRow')
                  : t('addRow')}
            </button>
            {modalConfig.editIndex > -1 && relatedDataInfo && relatedDataInfo.length > 0 && (
              <button
                onClick={() => setRowDetailsTab('relations')}
                className={`py-4 text-sm font-medium border-b-2 transition-colors flex items-center gap-2 ${rowDetailsTab === 'relations' ? `${tc.border} ${tc.textLight}` : 'border-transparent text-zinc-400 hover:text-zinc-200'}`}
              >
                <Network className="w-4 h-4" /> {t('relatedData')}
              </button>
            )}
          </div>
          <button
            onClick={() => setModalConfig({ isOpen: false })}
            className="text-zinc-500 hover:text-zinc-300 p-1 hover:bg-[#333] rounded"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {rowDetailsTab === 'details' ? (
          <>
            <form onSubmit={saveRowData} className="flex-1 overflow-auto p-6 space-y-5">
              {currentTableData.columns.map((col) => (
                <div key={col.name} className="flex flex-col gap-1.5">
                  <label className="text-xs font-medium text-zinc-400 flex items-center justify-between">
                    <span className="flex items-center gap-1.5">
                      {col.name} {col.isPrimary && <Key className="w-3 h-3 text-amber-500/70" />}
                    </span>
                    <span className="text-[10px] text-zinc-600 font-mono uppercase">
                      {col.type}
                    </span>
                  </label>
                  {modalConfig.viewOnly ? (
                    <div className="w-full bg-[#18181b] border border-[#333] rounded p-3 text-sm text-zinc-200 min-h-[40px] whitespace-pre-wrap word-break">
                      {formData[col.name] !== null &&
                      formData[col.name] !== undefined &&
                      formData[col.name] !== '' ? (
                        String(formData[col.name])
                      ) : (
                        <span className="text-zinc-600 font-mono text-xs">NULL</span>
                      )}
                    </div>
                  ) : col.isForeign ? (
                    <SelectField
                      className={baseSelectClass}
                      value={getInputValue(col.name)}
                      onChange={(e) => setFormData({ ...formData, [col.name]: e.target.value })}
                    >
                      <option value="">-- {t('valuePlaceholder')} --</option>
                      {databases[activeDb]?.[col.foreignTable]?.data?.map((r) => (
                        <option key={r[col.foreignCol]} value={r[col.foreignCol]}>
                          {r[col.foreignCol]} - {r.ad_soyad || r.urun_adi || r.isim || ''}
                        </option>
                      ))}
                    </SelectField>
                  ) : isBooleanColumn(col) ? (
                    <SelectField
                      className={baseSelectClass}
                      value={(() => {
                        const rawValue = getInputValue(col.name);
                        if (rawValue === '') return '';
                        return String(rawValue) === '1' || String(rawValue).toLowerCase() === 'true'
                          ? '1'
                          : '0';
                      })()}
                      onChange={(e) => setFormData({ ...formData, [col.name]: e.target.value })}
                      disabled={isAutoGeneratedColumn(col) && modalConfig.editIndex === -1}
                    >
                      <option value="">NULL</option>
                      <option value="1">True</option>
                      <option value="0">False</option>
                    </SelectField>
                  ) : isDateTimeColumn(col) ? (
                    <TemporalInputField
                      type="datetime-local"
                      className={baseFieldClass}
                      value={normalizeTemporalInputValue(getInputValue(col.name), 'datetime-local')}
                      onChange={(e) => setFormData({ ...formData, [col.name]: e.target.value })}
                      disabled={isAutoGeneratedColumn(col) && modalConfig.editIndex === -1}
                    />
                  ) : isDateColumn(col) ? (
                    <TemporalInputField
                      type="date"
                      className={baseFieldClass}
                      value={normalizeTemporalInputValue(getInputValue(col.name), 'date')}
                      onChange={(e) => setFormData({ ...formData, [col.name]: e.target.value })}
                      disabled={isAutoGeneratedColumn(col) && modalConfig.editIndex === -1}
                    />
                  ) : isTimeColumn(col) ? (
                    <TemporalInputField
                      type="time"
                      className={baseFieldClass}
                      value={normalizeTemporalInputValue(getInputValue(col.name), 'time')}
                      onChange={(e) => setFormData({ ...formData, [col.name]: e.target.value })}
                      disabled={isAutoGeneratedColumn(col) && modalConfig.editIndex === -1}
                    />
                  ) : isLongTextColumn(col) ? (
                    <textarea
                      className={baseTextAreaClass}
                      value={getInputValue(col.name)}
                      onChange={(e) => setFormData({ ...formData, [col.name]: e.target.value })}
                      disabled={isAutoGeneratedColumn(col) && modalConfig.editIndex === -1}
                      placeholder={
                        isAutoGeneratedColumn(col) ? t('autoGen') : t('valuePlaceholder')
                      }
                    />
                  ) : (
                    <input
                      type={isNumericColumnType(col) ? 'number' : 'text'}
                      className={baseFieldClass}
                      value={getInputValue(col.name)}
                      onChange={(e) => setFormData({ ...formData, [col.name]: e.target.value })}
                      disabled={isAutoGeneratedColumn(col) && modalConfig.editIndex === -1}
                      placeholder={isAutoGeneratedColumn(col) ? t('autoGen') : 'NULL'}
                    />
                  )}
                </div>
              ))}
            </form>
            <div className="p-4 border-t border-[#2e2e32] bg-[#18181b] flex justify-end items-center gap-2">
              <div className="flex gap-2">
                <button
                  type="button"
                  onClick={() => setModalConfig({ isOpen: false })}
                  className="px-4 py-2 text-xs font-medium text-zinc-300 border border-[#333] hover:bg-[#2e2e32] rounded"
                >
                  {modalConfig.viewOnly ? t('close') : t('cancel')}
                </button>
                {!modalConfig.viewOnly && (
                  <button
                    type="button"
                    onClick={saveRowData}
                    className={`px-4 py-2 text-xs font-medium text-white ${tc.bg} ${tc.hoverBg} rounded`}
                  >
                    {t('saveBtn')}
                  </button>
                )}
              </div>
            </div>
          </>
        ) : (
          <div className="flex-1 overflow-auto p-4 bg-[#18181b]">
            {relatedDataInfo.map((rel, i) => (
              <div key={i} className="mb-6">
                <div className="flex items-center gap-2 mb-3">
                  <LinkIcon className="w-4 h-4 text-blue-400" />
                  <h4 className="text-sm font-medium text-zinc-200">
                    {rel.tableName}{' '}
                    <span className="text-zinc-500 font-normal">
                      ({rel.rows.length} {t('records')})
                    </span>
                  </h4>
                </div>
                {rel.rows.length === 0 ? (
                  <div className="text-xs text-zinc-500 p-4 border border-[#333] border-dashed rounded text-center">
                    {t('noRecords')}
                  </div>
                ) : (
                  <div className="border border-[#333] rounded overflow-hidden">
                    <table className="w-full text-left text-xs whitespace-nowrap">
                      <thead className="bg-[#232323] text-zinc-400 border-b border-[#333]">
                        <tr>
                          {rel.cols.slice(0, 4).map((c) => (
                            <th
                              key={c.name}
                              className="px-3 py-1.5 font-normal border-r border-[#333] last:border-0"
                            >
                              {c.name}
                            </th>
                          ))}
                        </tr>
                      </thead>
                      <tbody className="divide-y divide-[#333]">
                        {rel.rows.map((r, idx) => (
                          <tr key={idx} className="hover:bg-[#2e2e32]">
                            {rel.cols.slice(0, 4).map((c) => (
                              <td
                                key={c.name}
                                className="px-3 py-1.5 text-zinc-300 border-r border-[#333] last:border-0 truncate max-w-[100px]"
                              >
                                {String(r[c.name])}
                              </td>
                            ))}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
