import {
  normalizeImportHeader,
  formatBytesValue as formatBytesValueUtil,
  formatIniSizeValue as formatIniSizeValueUtil,
  formatExecutionTimeValue as formatExecutionTimeValueUtil,
  parseCsvText,
  loadSqlTextFromFile as loadSqlTextFromFileUtil,
  splitSqlStatements,
  parseExcelRows as parseExcelRowsUtil,
} from '../../../utils/import.js';

export const normalizeImportedValue = (value, column, { isBooleanColumn, isNumericColumnType }) => {
  if (value === null || value === undefined) return null;
  const raw = typeof value === 'string' ? value.trim() : value;
  if (raw === '') return null;

  if (isBooleanColumn(column)) {
    const boolText = String(raw).toLowerCase();
    if (['1', 'true', 'yes', 'y', 'on'].includes(boolText)) return 1;
    if (['0', 'false', 'no', 'n', 'off'].includes(boolText)) return 0;
  }

  if (isNumericColumnType(column)) {
    const numeric = Number(raw);
    if (!Number.isNaN(numeric)) return numeric;
  }

  return raw;
};

export const buildImportMeta = (modalType, t) => ({
  accept: modalType === 'import_db' ? '.sql,.zip,.sql.zip' : '.csv,.xlsx,.xls,.sql,.zip,.sql.zip',
  dropLabel: modalType === 'import_db' ? t('dropSqlZipHere') : t('dropImportHere'),
  formatHint: modalType === 'import_db' ? t('importDbFormats') : t('importTableFormats'),
});

export default function useWorkspaceImportExportActions({
  t,
  loadJsZip,
  loadXlsx,
  modalConfig,
  setModalConfig,
  importFileInputRef,
  isImporting,
  setIsImporting,
  setIsImportDragActive,
  setImportLimitsError,
  importLimits,
  currentTableData,
  activeDb,
  activeTable,
  isAutoGeneratedColumn,
  isBooleanColumn,
  isNumericColumnType,
  quoteIdentifier,
  escapeLiteral,
  callApi,
  buildConnectionPayload,
  executeSql,
  refreshSchemas,
  ensureDatabaseTablesLoaded,
  refreshActiveTable,
  showToast,
  databases,
  hiddenColumns,
  processedData,
  selectedRows,
  setSqlQuery,
  aiPrompt,
  setAiPrompt,
  setIsAiLoading,
}) {
  const formatBytesValue = (bytes) => formatBytesValueUtil(bytes, t('unlimited'));
  const formatIniSizeValue = (entry) => formatIniSizeValueUtil(entry, t('unlimited'));
  const formatExecutionTimeValue = (seconds) =>
    formatExecutionTimeValueUtil(seconds, t('unlimited'));
  const loadSqlTextFromFile = (file) =>
    loadSqlTextFromFileUtil(file, {
      loadJsZip,
      missingSqlError: t('importSqlMissing'),
      unsupportedFormatError: t('unsupportedImportFormat'),
    });
  const parseExcelRows = (file) => parseExcelRowsUtil(file, { loadXlsx });

  const importRowsIntoCurrentTable = async (rows) => {
    if (!activeDb || !activeTable || !currentTableData) {
      throw new Error('No active table selected for import.');
    }
    if (!Array.isArray(rows) || rows.length === 0) {
      throw new Error(t('importNoRows'));
    }

    const sourceRowKeys = Object.keys(rows[0] || {});
    const sourceKeyMap = new Map(sourceRowKeys.map((key) => [normalizeImportHeader(key), key]));
    const mappedColumns = currentTableData.columns
      .filter((column) => !isAutoGeneratedColumn(column))
      .map((column) => ({
        column,
        sourceKey: sourceKeyMap.get(normalizeImportHeader(column.name)),
      }))
      .filter((entry) => Boolean(entry.sourceKey));

    if (mappedColumns.length === 0) {
      throw new Error(t('importNoMatchingColumns'));
    }

    const columnSql = mappedColumns.map((entry) => quoteIdentifier(entry.column.name)).join(', ');
    const batchSize = 100;
    let inserted = 0;

    for (let start = 0; start < rows.length; start += batchSize) {
      const chunk = rows
        .slice(start, start + batchSize)
        .filter((row) =>
          mappedColumns.some((entry) => String(row[entry.sourceKey] ?? '').trim() !== ''),
        );
      if (chunk.length === 0) continue;

      const valuesSql = chunk
        .map((row) => {
          const tuple = mappedColumns.map((entry) =>
            escapeLiteral(
              normalizeImportedValue(row[entry.sourceKey], entry.column, {
                isBooleanColumn,
                isNumericColumnType,
              }),
            ),
          );
          return `(${tuple.join(', ')})`;
        })
        .join(', ');

      const insertSql = `INSERT INTO ${quoteIdentifier(activeTable)} (${columnSql}) VALUES ${valuesSql};`;
      await executeSql(insertSql, activeDb);
      inserted += chunk.length;
    }

    if (inserted === 0) {
      throw new Error(t('importNoRows'));
    }

    return inserted;
  };

  const executeImportedSqlText = async (sqlText, databaseName = '') => {
    const statements = splitSqlStatements(sqlText).filter(
      (statement) => statement !== '' && !statement.startsWith('--'),
    );

    if (statements.length === 0) {
      throw new Error(t('importNoStatements'));
    }

    let executed = 0;
    for (const statement of statements) {
      await executeSql(statement, databaseName);
      executed += 1;
    }
    return executed;
  };

  const closeImportModal = () => {
    setModalConfig({ isOpen: false, type: null });
    setIsImportDragActive(false);
    setImportLimitsError('');
    if (importFileInputRef.current) {
      importFileInputRef.current.value = '';
    }
  };

  const handleImportFile = async (file) => {
    if (!file || isImporting) return;

    const fileName = String(file.name || '').toLowerCase();
    const isSqlLike = fileName.endsWith('.sql') || fileName.endsWith('.zip');

    setIsImporting(true);
    try {
      if (modalConfig.type === 'import_db') {
        if (!isSqlLike) {
          throw new Error(t('importDbOnlySql'));
        }
        const sqlText = await loadSqlTextFromFile(file);
        const executed = await executeImportedSqlText(sqlText, '');
        await refreshSchemas();
        if (activeDb) {
          await ensureDatabaseTablesLoaded(activeDb, { force: true });
        }
        showToast(t('importSuccessStatements').replace('{count}', String(executed)), 'success');
      } else if (modalConfig.type === 'import') {
        if (isSqlLike) {
          const sqlText = await loadSqlTextFromFile(file);
          const executed = await executeImportedSqlText(sqlText, activeDb || '');
          await refreshSchemas();
          if (activeDb) {
            await ensureDatabaseTablesLoaded(activeDb, { force: true });
          }
          if (activeDb && activeTable) {
            await refreshActiveTable();
          }
          showToast(t('importSuccessStatements').replace('{count}', String(executed)), 'success');
        } else if (fileName.endsWith('.csv')) {
          const rows = parseCsvText(await file.text());
          const count = await importRowsIntoCurrentTable(rows);
          await refreshActiveTable();
          showToast(t('importSuccessRows').replace('{count}', String(count)), 'success');
        } else if (fileName.endsWith('.xlsx') || fileName.endsWith('.xls')) {
          const rows = await parseExcelRows(file);
          const count = await importRowsIntoCurrentTable(rows);
          await refreshActiveTable();
          showToast(t('importSuccessRows').replace('{count}', String(count)), 'success');
        } else {
          throw new Error(t('unsupportedImportFormat'));
        }
      }

      closeImportModal();
    } catch (error) {
      showToast(error.message || t('importFailed'), 'error');
    } finally {
      setIsImporting(false);
      setIsImportDragActive(false);
    }
  };

  const openImportFilePicker = () => {
    if (isImporting) return;
    importFileInputRef.current?.click();
  };

  const handleImportFileInputChange = (event) => {
    const file = event.target.files?.[0];
    if (file) {
      handleImportFile(file);
    }
  };

  const handleImportDragOver = (event) => {
    event.preventDefault();
    if (!isImporting) setIsImportDragActive(true);
  };

  const handleImportDragLeave = (event) => {
    event.preventDefault();
    setIsImportDragActive(false);
  };

  const handleImportDrop = (event) => {
    event.preventDefault();
    setIsImportDragActive(false);
    if (isImporting) return;
    const file = event.dataTransfer?.files?.[0];
    if (file) {
      handleImportFile(file);
    }
  };

  const downloadFile = (content, fileName, mimeType) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.setAttribute('href', url);
    link.setAttribute('download', fileName);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const exportToCSV = (dataArray, fileName) => {
    if (!dataArray || dataArray.length === 0) return showToast(t('noRecords'), 'error');
    const headers = Object.keys(dataArray[0]).filter(
      (k) => k !== '_origIndex' && !hiddenColumns.has(k),
    );
    const csvRows = dataArray.map((row) =>
      headers.map((fieldName) => JSON.stringify(row[fieldName] ?? '')).join(','),
    );
    const csvContent = [headers.join(','), ...csvRows].join('\n');
    downloadFile(csvContent, `${fileName}.csv`, 'text/csv;charset=utf-8;');
    showToast(`${fileName}.csv downloaded!`, 'success');
  };

  const exportToJSON = (dataArray, fileName) => {
    if (!dataArray || dataArray.length === 0) return showToast(t('noRecords'), 'error');
    const cleanData = dataArray.map((row) => {
      const newRow = { ...row };
      delete newRow._origIndex;
      hiddenColumns.forEach((hc) => delete newRow[hc]);
      return newRow;
    });
    downloadFile(
      JSON.stringify(cleanData, null, 2),
      `${fileName}.json`,
      'application/json;charset=utf-8;',
    );
    showToast(`${fileName}.json downloaded!`, 'success');
  };

  const exportToSQL = (dataArray, dbName, tableName) => {
    if (!dataArray || dataArray.length === 0) return showToast(t('noRecords'), 'error');
    const headers = Object.keys(dataArray[0]).filter(
      (k) => k !== '_origIndex' && !hiddenColumns.has(k),
    );

    let sqlContent = `-- DB: ${dbName}\n-- Table: ${tableName}\n-- Date: ${new Date().toLocaleString()}\n\n`;

    dataArray.forEach((row) => {
      const vals = headers.map((h) => {
        const v = row[h];
        if (v === null || v === undefined) return 'NULL';
        if (typeof v === 'number') return v;
        return `'${String(v).replace(/'/g, "''")}'`;
      });
      sqlContent += `INSERT INTO "${tableName}" (${headers.map((h) => `"${h}"`).join(', ')}) VALUES (${vals.join(', ')});\n`;
    });

    downloadFile(sqlContent, `${tableName}_dump.sql`, 'text/sql;charset=utf-8;');
    showToast(`${tableName}_dump.sql downloaded!`, 'success');
  };

  const toExportSqlLiteral = (value) => {
    if (value === null || value === undefined) return 'NULL';
    if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL';
    if (typeof value === 'boolean') return value ? '1' : '0';
    return `'${String(value).replace(/'/g, "''")}'`;
  };

  const loadAllRowsForTableForExport = async (dbName, tableName) => {
    const perPage = 200;
    let page = 1;
    let expectedRowCount = null;
    const rows = [];

    for (;;) {
      const result = await callApi('browse_table', {
        connection: buildConnectionPayload(dbName),
        table: tableName,
        page,
        perPage,
        includeRowCount: false,
        sort: null,
        filters: [],
      });

      if (
        expectedRowCount === null &&
        result.rowCount !== undefined &&
        result.rowCount !== null &&
        result.rowCount !== ''
      ) {
        const parsedRowCount = Number(result.rowCount);
        if (Number.isFinite(parsedRowCount) && parsedRowCount >= 0) {
          expectedRowCount = parsedRowCount;
        }
      }

      const pageRows = Array.isArray(result.rows) ? result.rows : [];
      rows.push(...pageRows);

      const expectedRowCountKnown =
        expectedRowCount !== null && Number.isFinite(expectedRowCount) && expectedRowCount >= 0;

      if (pageRows.length === 0) {
        break;
      }

      if (expectedRowCountKnown && rows.length >= expectedRowCount) {
        break;
      }

      if (!expectedRowCountKnown && !result.hasMore) {
        break;
      }

      page += 1;
    }

    return rows;
  };

  const handleExportDatabaseSql = async () => {
    if (!activeDb) {
      showToast('No active database selected.', 'error');
      return;
    }

    const tableEntries = Object.entries(databases[activeDb] || {})
      .filter(([, table]) => (table?.type || 'table') !== 'view')
      .map(([tableName]) => tableName)
      .sort((a, b) => a.localeCompare(b));

    if (tableEntries.length === 0) {
      showToast(t('noRecords'), 'error');
      return;
    }

    try {
      const sections = [`-- DB: ${activeDb}`, `-- Exported at: ${new Date().toISOString()}`, ''];

      for (const tableName of tableEntries) {
        const allRows = await loadAllRowsForTableForExport(activeDb, tableName);
        sections.push(`-- Table: ${tableName} (${allRows.length} rows)`);

        if (allRows.length === 0) {
          sections.push('');
          continue;
        }

        const headers = Object.keys(allRows[0]).filter((key) => key !== '_origIndex');
        const quotedTable = quoteIdentifier(tableName);
        const columnSql = headers.map((header) => quoteIdentifier(header)).join(', ');

        allRows.forEach((row) => {
          const valueSql = headers.map((header) => toExportSqlLiteral(row[header])).join(', ');
          sections.push(`INSERT INTO ${quotedTable} (${columnSql}) VALUES (${valueSql});`);
        });

        sections.push('');
      }

      downloadFile(sections.join('\n'), `${activeDb}_full_dump.sql`, 'text/sql;charset=utf-8;');
      showToast(`${activeDb}_full_dump.sql downloaded!`, 'success');
      setModalConfig({ isOpen: false, type: null });
    } catch (error) {
      showToast(error.message || 'Database export failed.', 'error');
    }
  };

  const handleExportTable = (format = 'csv') => {
    const dataToExport =
      selectedRows.size > 0
        ? processedData.filter((row) => selectedRows.has(row._origIndex))
        : processedData;
    const fileName = selectedRows.size > 0 ? `${activeTable}_selected` : activeTable;
    if (format === 'csv') exportToCSV(dataToExport, fileName);
    if (format === 'json') exportToJSON(dataToExport, fileName);
    if (format === 'sql') exportToSQL(dataToExport, activeDb, activeTable);
    setModalConfig({ isOpen: false, type: null });
  };

  const handleAiGenerate = (e) => {
    e.preventDefault();
    if (!aiPrompt.trim()) return;
    setIsAiLoading(true);
    setTimeout(() => {
      const generatedSql = `-- AI: "${aiPrompt}"\nSELECT \n  * \nFROM \n  "${activeTable || 'table_name'}" \nWHERE \n  1=1\nORDER BY \n  id DESC \nLIMIT 10;`;
      setSqlQuery(generatedSql);
      setIsAiLoading(false);
      setAiPrompt('');
      showToast(t('aiSuccess'), 'success');
    }, 1500);
  };

  const isImportModalOpen =
    modalConfig.isOpen && (modalConfig.type === 'import' || modalConfig.type === 'import_db');
  const importMeta = buildImportMeta(modalConfig.type, t);
  const importAccept = importMeta.accept;
  const importDropLabel = importMeta.dropLabel;
  const importFormatHint = importMeta.formatHint;
  const importLimitsRows = [
    {
      label: t('effectiveUploadLimit'),
      value: formatIniSizeValue(importLimits?.effectiveUploadLimit),
    },
    { label: t('uploadMaxFilesize'), value: formatIniSizeValue(importLimits?.uploadMaxFilesize) },
    { label: t('postMaxSize'), value: formatIniSizeValue(importLimits?.postMaxSize) },
    { label: t('memoryLimit'), value: formatIniSizeValue(importLimits?.memoryLimit) },
    { label: t('maxFileUploads'), value: importLimits?.maxFileUploads ?? '--' },
    {
      label: t('maxExecutionTime'),
      value: formatExecutionTimeValue(importLimits?.maxExecutionTime),
    },
  ];

  return {
    formatBytesValue,
    formatIniSizeValue,
    formatExecutionTimeValue,
    closeImportModal,
    handleImportFileInputChange,
    openImportFilePicker,
    handleImportDragOver,
    handleImportDragLeave,
    handleImportDrop,
    exportToCSV,
    exportToJSON,
    exportToSQL,
    handleExportDatabaseSql,
    handleExportTable,
    handleAiGenerate,
    isImportModalOpen,
    importAccept,
    importDropLabel,
    importFormatHint,
    importLimitsRows,
  };
}
